<a href="https://colab.research.google.com/github/koliby777/Pytorch_tutorials/blob/main/Tensors_tutorial.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
# For tips on running notebooks in Google Colab, see
# https://pytorch.org/tutorials/beginner/colab
%matplotlib inline

[Learn the Basics](intro.html) \|\|
[Quickstart](quickstart_tutorial.html) \|\| **Tensors** \|\| [Datasets &
DataLoaders](data_tutorial.html) \|\|
[Transforms](transforms_tutorial.html) \|\| [Build
Model](buildmodel_tutorial.html) \|\|
[Autograd](autogradqs_tutorial.html) \|\|
[Optimization](optimization_tutorial.html) \|\| [Save & Load
Model](saveloadrun_tutorial.html)

Tensors
=======

Tensors are a specialized data structure that are very similar to arrays
and matrices. In PyTorch, we use tensors to encode the inputs and
outputs of a model, as well as the model's parameters.

Tensors are similar to [NumPy's](https://numpy.org/) ndarrays, except
that tensors can run on GPUs or other hardware accelerators. In fact,
tensors and NumPy arrays can often share the same underlying memory,
eliminating the need to copy data (see
`bridge-to-np-label`{.interpreted-text role="ref"}). Tensors are also
optimized for automatic differentiation (we\'ll see more about that
later in the [Autograd](autogradqs_tutorial.html) section). If you're
familiar with ndarrays, you'll be right at home with the Tensor API. If
not, follow along!


# NumPy's ndarrays

In [ ]:
import numpy as np
a = np.array([1, 2, 3, 4, 5])
print(a)
# Výstup: [1 2 3 4 5]
b = np.array([[1, 2, 3], [4, 5, 6]])
print(b)
# Výstup:
# [[1 2 3]
#  [4 5 6]]
c = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])
print(c)
# Výstup:
# [[[1 2]
#   [3 4]]
#
#  [[5 6]
#   [7 8]]]
print(a[1:4])  # Výstup: [2 3 4]
print(b[:, 1])  # Výstup: [2 5]
print(a + 10)  # Výstup: [11 12 13 14 15]
print(b * 2)  # Výstup:
# [[ 2  4  6]
#  [ 8 10 12]]
print(np.sum(a))  # Výstup: 15
print(np.mean(b))  # Výstup: 3.5


[1 2 3 4 5]
[[1 2 3]
 [4 5 6]]
[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]
[2 3 4]
[2 5]
[11 12 13 14 15]
[[ 2  4  6]
 [ 8 10 12]]
15
3.5


# Autograd

In [ ]:
import torch

# Vytvoření tenzoru
x = torch.tensor([1.0, 2.0, 3.0], requires_grad=True)


In [ ]:
print(x)

tensor([1., 2., 3.], requires_grad=True)


In [ ]:
# Provádění operací
y = x + 2
y

tensor([3., 4., 5.], grad_fn=<AddBackward0>)

In [ ]:
z = y * y * 2
z

tensor([18., 32., 50.], grad_fn=<MulBackward0>)

In [ ]:
out = z.mean()
print(out)


tensor(33.3333, grad_fn=<MeanBackward0>)


In [ ]:
# Zpětný průchod
out.backward()

In [ ]:
# Gradienty jsou uloženy v .grad
print(x.grad)

tensor([4.0000, 5.3333, 6.6667])


jinak ....

In [ ]:
x = torch.tensor([0., 1.], requires_grad=True)
x

tensor([0., 1.], requires_grad=True)

In [ ]:
out = x[0]**3 + x[1]**3
out

tensor(1., grad_fn=<AddBackward0>)

In [ ]:
out.backward()

In [ ]:
print(x.grad)

tensor([0., 3.])


1 rozmer

In [ ]:
x = torch.tensor([1.], requires_grad=True)
print(x)
out = x[0]**2
print(out)
out.backward()
print(-x.grad)  # menit ve smeru opaku gradientu

tensor([1.], requires_grad=True)
tensor(1., grad_fn=<PowBackward0>)
tensor([-2.])


# Tensors zde

In [ ]:
import torch
import numpy as np

Initializing a Tensor
=====================

Tensors can be initialized in various ways. Take a look at the following
examples:

**Directly from data**

Tensors can be created directly from data. The data type is
automatically inferred.


In [ ]:
data = [[1, 2],[3, 4]]
x_data = torch.tensor(data)
data, x_data

([[1, 2], [3, 4]],
 tensor([[1, 2],
         [3, 4]]))

**From a NumPy array**

Tensors can be created from NumPy arrays (and vice versa - see
`bridge-to-np-label`{.interpreted-text role="ref"}).


In [ ]:
np_array = np.array(data)
x_np = torch.from_numpy(np_array)
np_array, x_np

(array([[1, 2],
        [3, 4]]),
 tensor([[1, 2],
         [3, 4]]))

**From another tensor:**

The new tensor retains the properties (shape, datatype) of the argument
tensor, unless explicitly overridden.


In [ ]:
x_ones = torch.zeros_like(x_data) # retains the properties of x_data
print(f"Zeros Tensor: \n {x_ones} \n")

x_rand = torch.rand_like(x_data, dtype=torch.float) # overrides the datatype of x_data
print(f"Random Tensor: \n {x_rand} \n")

Zeros Tensor: 
 tensor([[0, 0],
        [0, 0]]) 

Random Tensor: 
 tensor([[0.2329, 0.2559],
        [0.7968, 0.0114]]) 



**With random or constant values:**

*`shape` is a tuple of tensor dimensions*. In the functions below, it
determines the dimensionality of the output tensor.


In [ ]:
shape = (2,3,)  # toto je tuple !!!!!!!

rand_tensor = torch.rand(shape)
ones_tensor = torch.ones(shape)
zeros_tensor = torch.zeros(shape)

print(f"Random Tensor: \n {rand_tensor} \n")
print(f"Ones Tensor: \n {ones_tensor} \n")
print(f"Zeros Tensor: \n {zeros_tensor}")

Random Tensor: 
 tensor([[0.1654, 0.3613, 0.3649],
        [0.3417, 0.2044, 0.7543]]) 

Ones Tensor: 
 tensor([[1., 1., 1.],
        [1., 1., 1.]]) 

Zeros Tensor: 
 tensor([[0., 0., 0.],
        [0., 0., 0.]])


------------------------------------------------------------------------


Attributes of a Tensor
======================

Tensor attributes describe their shape, datatype, and the device on
which they are stored.


In [ ]:
tensor = torch.rand(3,4)
print(tensor)
print(f"Shape of tensor: {tensor.shape}")
print(f"Datatype of tensor: {tensor.dtype}")
print(f"Device tensor is stored on: {tensor.device}")

tensor([[0.2660, 0.6064, 0.3325, 0.8130],
        [0.6854, 0.6583, 0.9934, 0.7450],
        [0.0293, 0.1604, 0.2829, 0.1311]])
Shape of tensor: torch.Size([3, 4])
Datatype of tensor: torch.float32
Device tensor is stored on: cpu


------------------------------------------------------------------------


Operations on Tensors
=====================

Over 100 tensor operations, including arithmetic, linear algebra, matrix
manipulation (transposing, indexing, slicing), sampling and more are
comprehensively described
[here](https://pytorch.org/docs/stable/torch.html).

Each of these operations can be run on the GPU (at typically higher
speeds than on a CPU). If you're using Colab, allocate a GPU by going to
Runtime \> Change runtime type \> GPU.

By default, tensors are created on the CPU. We need to explicitly move
tensors to the GPU using `.to` method (after checking for GPU
availability). Keep in mind that copying large tensors across devices
can be expensive in terms of time and memory!


In [ ]:
# We move our tensor to the GPU if available
if torch.cuda.is_available():
    tensor = tensor.to("cuda")
torch.cuda.is_available()

False

Try out some of the operations from the list. If you\'re familiar with
the NumPy API, you\'ll find the Tensor API a breeze to use.


**Standard numpy-like indexing and slicing:**


In [ ]:
tensor = torch.rand(4, 4)
print(tensor)
print(f"First row: {tensor[0]}")
print(f"First column: {tensor[:, 0]}")
print(f"Last column: {tensor[..., -1]}")
tensor[:,1] = 10
print(tensor)
tensor[2,:] = -25
print(tensor)

tensor([[0.6158, 0.8453, 0.6134, 0.9060],
        [0.8773, 0.8111, 0.4401, 0.3216],
        [0.2296, 0.0506, 0.6183, 0.9318],
        [0.9205, 0.2219, 0.2783, 0.1768]])
First row: tensor([0.6158, 0.8453, 0.6134, 0.9060])
First column: tensor([0.6158, 0.8773, 0.2296, 0.9205])
Last column: tensor([0.9060, 0.3216, 0.9318, 0.1768])
tensor([[ 0.6158, 10.0000,  0.6134,  0.9060],
        [ 0.8773, 10.0000,  0.4401,  0.3216],
        [ 0.2296, 10.0000,  0.6183,  0.9318],
        [ 0.9205, 10.0000,  0.2783,  0.1768]])
tensor([[  0.6158,  10.0000,   0.6134,   0.9060],
        [  0.8773,  10.0000,   0.4401,   0.3216],
        [-25.0000, -25.0000, -25.0000, -25.0000],
        [  0.9205,  10.0000,   0.2783,   0.1768]])


**Joining tensors** You can use `torch.cat` to concatenate a sequence of
tensors along a given dimension. See also
[torch.stack](https://pytorch.org/docs/stable/generated/torch.stack.html),
another tensor joining operator that is subtly different from
`torch.cat`.


In [ ]:
x = torch.randn(2, 3)
print(x)
x = torch.stack((x, x)) # same as torch.stack((x, x), dim=0)
print(x)

x.size()
x = torch.stack((x, x), dim=1)
print(x)
x = torch.stack((x, x), dim=2)
print(x)
x = torch.stack((x, x), dim=-1)
print(x)

tensor([[ 0.2419,  0.7840, -1.3979],
        [ 0.7964,  0.0590,  0.6285]])
tensor([[[ 0.2419,  0.7840, -1.3979],
         [ 0.7964,  0.0590,  0.6285]],

        [[ 0.2419,  0.7840, -1.3979],
         [ 0.7964,  0.0590,  0.6285]]])
tensor([[[[ 0.2419,  0.7840, -1.3979],
          [ 0.7964,  0.0590,  0.6285]],

         [[ 0.2419,  0.7840, -1.3979],
          [ 0.7964,  0.0590,  0.6285]]],


        [[[ 0.2419,  0.7840, -1.3979],
          [ 0.7964,  0.0590,  0.6285]],

         [[ 0.2419,  0.7840, -1.3979],
          [ 0.7964,  0.0590,  0.6285]]]])
tensor([[[[[ 0.2419,  0.7840, -1.3979],
           [ 0.7964,  0.0590,  0.6285]],

          [[ 0.2419,  0.7840, -1.3979],
           [ 0.7964,  0.0590,  0.6285]]],


         [[[ 0.2419,  0.7840, -1.3979],
           [ 0.7964,  0.0590,  0.6285]],

          [[ 0.2419,  0.7840, -1.3979],
           [ 0.7964,  0.0590,  0.6285]]]],



        [[[[ 0.2419,  0.7840, -1.3979],
           [ 0.7964,  0.0590,  0.6285]],

          [[ 0.2419,  0.7840, 

In [ ]:
t1 = torch.cat([tensor, tensor, tensor], dim=1)
print(t1)

tensor([[  0.6158,  10.0000,   0.6134,   0.9060,   0.6158,  10.0000,   0.6134,
           0.9060,   0.6158,  10.0000,   0.6134,   0.9060],
        [  0.8773,  10.0000,   0.4401,   0.3216,   0.8773,  10.0000,   0.4401,
           0.3216,   0.8773,  10.0000,   0.4401,   0.3216],
        [-25.0000, -25.0000, -25.0000, -25.0000, -25.0000, -25.0000, -25.0000,
         -25.0000, -25.0000, -25.0000, -25.0000, -25.0000],
        [  0.9205,  10.0000,   0.2783,   0.1768,   0.9205,  10.0000,   0.2783,
           0.1768,   0.9205,  10.0000,   0.2783,   0.1768]])


**Arithmetic operations**


In [ ]:
tensor = torch.rand(2, 3)
print(tensor)
print(tensor.T)
# This computes the matrix multiplication between two tensors. y1, y2, y3 will have the same value
# ``tensor.T`` returns the transpose of a tensor
y1 = tensor @ tensor.T
y2 = tensor.matmul(tensor.T)
print(y1)
print(y2)

y3 = torch.rand_like(y1)
torch.matmul(tensor, tensor.T, out=y3)


tensor([[0.2115, 0.7941, 0.2065],
        [0.7364, 0.2007, 0.5058]])
tensor([[0.2115, 0.7364],
        [0.7941, 0.2007],
        [0.2065, 0.5058]])
tensor([[0.7181, 0.4196],
        [0.4196, 0.8383]])
tensor([[0.7181, 0.4196],
        [0.4196, 0.8383]])


tensor([[0.7181, 0.4196],
        [0.4196, 0.8383]])

In [ ]:


# This computes the element-wise product. z1, z2, z3 will have the same value
z1 = tensor * tensor
z2 = tensor.mul(tensor)
print(z1)
print(z2)

z3 = torch.rand_like(tensor)
torch.mul(tensor, tensor, out=z3)

tensor([[0.0447, 0.6307, 0.0427],
        [0.5422, 0.0403, 0.2559]])
tensor([[0.0447, 0.6307, 0.0427],
        [0.5422, 0.0403, 0.2559]])


tensor([[0.0447, 0.6307, 0.0427],
        [0.5422, 0.0403, 0.2559]])

**Single-element tensors**

If you have a one-element tensor, for example
by aggregating all values of a tensor into one value, you can convert it
to a Python numerical value using `item()`:


In [ ]:
sss = sum(tensor)
print(sss)
agg = tensor.sum()
agg_item = agg.item()
print(agg_item, type(agg_item))

tensor([0.9479, 0.9948, 0.7124])
2.6550631523132324 <class 'float'>


**In-place operations**

Operations that store the result into the
operand are called in-place. They are denoted by a `_` suffix. For
example: `x.copy_(y)`, `x.t_()`, will change `x`.


In [ ]:
print(f"{tensor} \n")
tensor.add_(5)
print(tensor)

tensor([[0.2115, 0.7941, 0.2065],
        [0.7364, 0.2007, 0.5058]]) 

tensor([[5.2115, 5.7941, 5.2065],
        [5.7364, 5.2007, 5.5058]])


<div style="background-color: #54c7ec; color: #fff; font-weight: 700; padding-left: 10px; padding-top: 5px; padding-bottom: 5px"><strong>NOTE:</strong></div>
<div style="background-color: #f3f4f7; padding-left: 10px; padding-top: 10px; padding-bottom: 10px; padding-right: 10px">
<p>In-place operations save some memory, but can be problematic when computing derivatives because of an immediate lossof history. Hence, their use is discouraged.</p>
</div>


------------------------------------------------------------------------


Bridge with NumPy {#bridge-to-np-label}
=================

Tensors on the CPU and NumPy arrays can share their underlying memory
locations, and changing one will change the other.


Tensor to NumPy array
=====================


In [ ]:
t = torch.ones(5)
print(f"t: {t}")
n = t.numpy()
print(f"n: {n}")

t: tensor([1., 1., 1., 1., 1.])
n: [1. 1. 1. 1. 1.]


A change in the tensor reflects in the NumPy array.


In [ ]:
t.add_(1)
print(f"t: {t}")
print(f"n: {n}")

t: tensor([2., 2., 2., 2., 2.])
n: [2. 2. 2. 2. 2.]


NumPy array to Tensor
=====================


In [ ]:
n = np.ones(5)
t = torch.from_numpy(n)
n, t

(array([1., 1., 1., 1., 1.]),
 tensor([1., 1., 1., 1., 1.], dtype=torch.float64))

Changes in the NumPy array reflects in the tensor.


In [ ]:
np.add(n, 1, out=n)
print(f"t: {t}")
print(f"n: {n}")

t: tensor([2., 2., 2., 2., 2.], dtype=torch.float64)
n: [2. 2. 2. 2. 2.]
